version: '3'

services:
  mongodb-dev-primary:
    image: 'mongo:5.0'
#    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/bitnami
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_USERNAME=user1
      - MONGODB_PASSWORD=pass1
      - MONGODB_DATABASE=db1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=rootpass1
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=rs1
      - MONGODB_AUTHORIZATION=enabled


#version: '3'
#services:
#  myapplication:
#    image: myapp:1.0
#    environment:
#    ports:
#      - 27017:27017
#  mongodb:
#    image: mongo:5.0
#    environment:
#      - MONGODB_ADVERTISED_HOSTNAME=localhost
#      - MONGODB_USERNAME=user1
#      - MONGODB_PASSWORD=pass1
#      - MONGODB_DATABASE=db1
#      - MONGODB_REPLICA_SET_MODE=primary
#      - MONGODB_ROOT_PASSWORD=rootpass1
#      - MONGODB_REPLICA_SET_KEY=replicasetkey123
#      - MONGODB_REPLICA_SET_NAME=rs1
#      - MONGODB_AUTHORIZATION=enabled